import type { Metadata } from "next";
import "./globals.css";
import { inter } from "../lib/fonts";
import { Provider } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main>

          <div className="w-full">
            <Provider >
              {children}
            </Provider>
          </div>

        </main>
      </body>
    </html>
  );
}
// bg - [#020716]
