import type { Metadata } from "next";
import "./globals.css";
import { inter } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}   bg-[#020716]`}>
        <main>

          <div className="w-full">
            {children}
          </div>
        </main>

      </body>
    </html>
  );
}
